name = "wittův modpack"
author = "brzykovec"
version = "1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "de5c8381105a822a6811c64633b15f4d20ad0cc1921b2260aa88ddc4e5020989"

[versions]
fabric = "0.16.13"
minecraft = "1.20.1"
