name = "wittův modpack"
author = "brzykovec"
version = "1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8578a7d7956832696d6788621ffcf50b694b8d74a7f99ea0e9b180dfd3687eaa"

[versions]
fabric = "0.16.13"
minecraft = "1.20.1"
