name = "wittův modpack"
author = "brzykovec"
version = "1.20.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f4ee1ec71ee5ef6de41baaa22fba27917a650348c1b0bf63cc165a37ceac9b9b"

[versions]
fabric = "0.16.13"
minecraft = "1.20.1"
